name: Push a debian package to Cloudsmith with OIDC
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  id-token: write      # Necessary to GH Identity Provider to write the JWT token which Cloudsmith needs to read
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    name: Push a Debian package to Cloudsmith using OIDC to authenticate
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Create Debian package
        run: |
          mkdir -p test/cloudsmith-debian-example-1.0.0-amd64/DEBIAN
          echo 'Package: cloudsmith-debian-example
          Version: 1.0.0
          Section: base
          Priority: optional
          Architecture: amd64
          Maintainer: Your Name <you@example.com>
          Description: This is a Cloudsmith Debian example package
          ' > test/cloudsmith-debian-example-1.0.0-amd64/DEBIAN/control
          mkdir -p test/cloudsmith-debian-example-1.0.0-amd64/usr/local/bin
          echo '#!/bin/bash\necho "Hello, Cloudsmith!"' > test/cloudsmith-debian-example-1.0.0-amd64/usr/local/bin/cloudsmith-debian-example
          chmod 755 test/cloudsmith-debian-example-1.0.0-amd64/usr/local/bin/cloudsmith-debian-example
          dpkg-deb --build test/cloudsmith-debian-example-1.0.0-amd64

      - name: Get OIDC token
        run: |
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq -r '.value')
          token=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":\"$value\", \"service_slug\":\"github-actions\"}" https://api.cloudsmith.io/openid/github-actions/ | jq -r '.token')
          echo "CLOUDSMITH_API_KEY=$token" >> $GITHUB_ENV

      - name: Cloudsmith Push Debian Package
        uses: cloudsmith-io/action@v0.5.3
        with:
          command: 'push'
          format: 'deb'
          owner: 'arshad-qureshi'             # Your Cloudsmith account name or org name (namespace)
          repo: 'github-actions'         # Your Cloudsmith Repository name (slug)
          distro: 'debian'     # Your Distribution  (i.e Debian, Ubuntu)
          release: 'buster'         # Your Distribution Release (i.e xenial, buster)
          republish: 'true'          # needed if version is not changing
          file: 'test/cloudsmith-debian-example-1.0.0-amd64.deb'  # debian package filename
