name: Push a debian package to Cloudsmith with OIDC
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  id-token: write      # Necessary to GH Identity Provider to write the JWT token which Cloudsmith needs to read
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    name: Push a Debian package to Cloudsmith using OIDC to authenticate
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get OIDC token
        run: |
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq '.value')
          token=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":$value, \"service_slug\":\"SERVICE_ACCOUNT_SLUG\"}" https://api.cloudsmith.io/openid/ORGANIZATION/ | jq -r '.token')
          curl --request GET --url https://api.cloudsmith.io/v1/user/self/ --header "X-Api-Key:Bearer $token" --header 'accept: application/json'
                    
          echo "CLOUDSMITH_API_KEY=$token" >> $GITHUB_ENV
          
      - name: Cloudsmith Push Debian Package
        uses: cloudsmith-io/action@v0.5.3
        with:
          command: 'push'
          format: 'deb'
          owner: 'DEMO_ORG'             # Your Cloudsmith account name or org name (namespace)
          repo: 'DEMO_REPOSITORY'         # Your Cloudsmith Repository name (slug)
          distro: 'debian'     # Your Distribution  (i.e Debian, Ubuntu)
          release: 'buster'         # Your Distribution Release (i.e xenial, buster)
          republish: 'true'          # needed if version is not changing
          file: 'test/cloudsmith-debian-example-1.0.0-amd64.deb'  # debian package filename
