name: Push a Debian package to Cloudsmith with OIDC
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    name: Push a Debian package to Cloudsmith using OIDC to authenticate
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Create Debian package
        run: |
          mkdir -p test/cloudsmith-debian-example-1.0.0-amd64/DEBIAN
          echo 'Package: cloudsmith-debian-example
          Version: 1.0.0
          Section: base
          Priority: optional
          Architecture: amd64
          Maintainer: Your Name <you@example.com>
          Description: This is a Cloudsmith Debian example package
          ' > test/cloudsmith-debian-example-1.0.0-amd64/DEBIAN/control
          mkdir -p test/cloudsmith-debian-example-1.0.0-amd64/usr/local/bin
          echo '#!/bin/bash\necho "Hello, Cloudsmith!"' > test/cloudsmith-debian-example-1.0.0-amd64/usr/local/bin/cloudsmith-debian-example
          chmod 755 test/cloudsmith-debian-example-1.0.0-amd64/usr/local/bin/cloudsmith-debian-example
          dpkg-deb --build test/cloudsmith-debian-example-1.0.0-amd64

      - name: Verify Debian package creation
        run: |
          ls -la test
          ls -la test/cloudsmith-debian-example-1.0.0-amd64.deb

      - name: Get OIDC token
        id: get_oidc_token
        run: |
          echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}"
          echo "ACTIONS_ID_TOKEN_REQUEST_URL: ${ACTIONS_ID_TOKEN_REQUEST_URL}"
          
          response=$(curl -s -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=api://AzureADTokenExchange")
          echo "OIDC Token Response: $response"
          
          oidc_token=$(echo $response | jq -r '.value')
          echo "OIDC Token: $oidc_token"
          
          echo "OIDC_TOKEN=$oidc_token" >> $GITHUB_ENV
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange"

      - name: Request Cloudsmith JWT Token
        id: request_jwt
        run: |
          echo "Requesting Cloudsmith JWT token"
          echo "OIDC Token being sent: ${{ env.OIDC_TOKEN }}"
          
          response=$(curl -s -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":\"${{ env.OIDC_TOKEN }}\", \"service_slug\":\"github-actions\"}" "https://api.cloudsmith.io/openid/interview-arshad-qureshi/")
          echo "JWT Response: $response"
          
          cloudsmith_token=$(echo $response | jq -r '.token')
          echo "JWT Token: $cloudsmith_token"
          echo "CLOUDSMITH_API_KEY=$cloudsmith_token" >> $GITHUB_ENV

      - name: Cloudsmith Push Debian Package
        uses: cloudsmith-io/action@v0.5.3
        with:
          command: 'push'
          format: 'deb'
          owner: 'arshad-qureshi'
          repo: 'github-actions'
          distro: 'debian'
          release: 'buster'
          republish: 'true'
          file: 'test/cloudsmith-debian-example-1.0.0-amd64.deb'
