name: Package and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Create dummy npm package
        run: |
          mkdir dummy-package
          cd dummy-package
          echo '{
            "name": "dummy-package",
            "version": "1.0.0",
            "description": "A dummy npm package",
            "main": "index.js",
            "scripts": {
              "build": "echo Building...",
              "test": "echo Testing..."
            },
            "author": "Your Name",
            "license": "MIT"
          }' > package.json
          echo 'console.log("Hello, world!");' > index.js
          npm install

      - name: Build package
        run: |
          cd dummy-package
          npm run build  # Adjust if needed

      - name: Create npm package
        run: |
          cd dummy-package
          npm pack  # Create the .tgz package file

      - name: Request OIDC Token
        id: get_oidc_token
        run: |
          echo "Requesting OIDC token"
          oidc_token=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq -r '.value')
          echo "::set-output name=oidc_token::$oidc_token"

      - name: Request Cloudsmith JWT Token
        id: get_cloudsmith_token
        run: |
          echo "Requesting Cloudsmith JWT token"
          cloudsmith_jwt=$(curl -s -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":\"${{ steps.get_oidc_token.outputs.oidc_token }}\", \"service_slug\":\"github-actions\"}" https://api.cloudsmith.io/openid/github-actions/ | jq -r '.token')
          echo "::set-output name=cloudsmith_token::$cloudsmith_jwt"

      - name: Install Cloudsmith CLI
        run: |
          pip install cloudsmith-cli

      - name: Publish package to Cloudsmith
        run: |
          cd dummy-package
          PACKAGE_FILE=$(ls *.tgz)
          cloudsmith push npm github-actions/interview-arshad-qureshi $PACKAGE_FILE
        env:
          CLOUDSMITH_API_KEY: ${{ steps.get_cloudsmith_token.outputs.cloudsmith_token }}
